# GitHub Pages configuration for TicketHive API Documentation

# Site settings
title: TicketHive API Documentation
description: Comprehensive API documentation for TicketHive event ticket management platform
url: "https://hnagnurtme.github.io"
baseurl: "/TicketHive"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.sh"
  - .gitignore

# Include files that start with underscores
include:
  - _redirects
  - .nojekyll

# Disable Jekyll processing for certain directories
# This ensures Swagger UI files are served as-is
kramdown:
  input: GFM
  syntax_highlighter: rouge

# GitHub Pages specific settings
github_username: hnagnurtme
repository: TicketHive

# Custom variables
api_title: "TicketHive API"
api_version: "v1"
api_description: "Event ticket management platform API"

# Disable processing for swagger-ui directory
sass:
  style: compressed

# Set default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default