name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # 🔑 Generate RSA keys before build
    - name: Generate RSA keys
      run: |
        mkdir -p ./src/TicketHive.Api/Keys
        openssl genrsa -out ./src/TicketHive.Api/Keys/rsa_private.pem 2048
        openssl rsa -in ./src/TicketHive.Api/Keys/rsa_private.pem -pubout -out ./src/TicketHive.Api/Keys/rsa_public.pem

    - name: Restore dependencies
      run: dotnet restore

    - name: Build tests
      run: dotnet build ./tests/TicketHive.Tests/TicketHive.Tests.csproj --configuration Release

    - name: Run tests
      run: dotnet test ./tests/TicketHive.Tests/TicketHive.Tests.csproj --no-build --configuration Release
